asshu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from teachers.views import *
from base.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    # venues
    path("",home,name='home'),
    path("teachers/", include("teachers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.



class User(AbstractUser):
    is_school = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    thumbnail = models.ImageField(upload_to="profile/", blank=True, null=True)


class Region(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class District(models.Model):
    name = models.CharField(max_length=100)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from dashboard.models import *
from accounts.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm



class SchoolRegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=100)
    phone = forms.CharField(max_length=20, required=False)

    class Meta:
        model = User
        fields = [
            "email",
            "first_name",
            "last_name",
            "phone",
            "username",
            "password1",
            "password2",
            "is_school",
        ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login
from accounts.decorators import school_required, anonymous_required, staff_required
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm

from django.contrib import messages
from .forms import SchoolRegistrationForm

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash


# from accounts.forms import AthleteFilterForm


@staff_required
def school_registration(request):
    if request.method == "POST":
        form = SchoolRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(
                commit=False
            )  # Create the user object without saving to the database
            user.is_school = True  # Set is_school to True
            user.save()  # Save the user object with is_school set to True

            # Log in the user
            login(request, user)

            return redirect("confirmation")
    else:
        form = SchoolRegistrationForm()
    return render(request, "register.html", {"form": form})


# Create your views here.
@anonymous_required
def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)

            if user.is_school:
                messages.success(request, "School login successful.")
                return redirect("school_dashboard")
            elif user.is_admin:
                messages.success(request, "Officer login successful.")
                return redirect("officer_dashboard")
            else:
                messages.success(request, "Login successful.")
                return redirect(
                    "dashboard"
                )  # Adjust the URL name for your dashboard view
        else:
            messages.error(request, "Error in login. Please check your credentials.")
    else:
        form = AuthenticationForm()
    return render(request, "login.html", {"form": form})


def user_logout(request):
    # if user.is_authenticated:
    logout(request)
    return redirect("login")


def custom_404(request, exception):
    return render(request, "account/custom404.html", {}, status=404)



#  auth views
@anonymous_required
def school_registration(request):
    if request.method == "POST":
        form = SchoolRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(
                commit=False
            )  # Create the user object without saving to the database
            user.is_school = True  # Set is_school to True
            user.save()  # Save the user object with is_school set to True

            # Log in the user
            login(request, user)

            return redirect("new_school")
    else:
        form = SchoolRegistrationForm()
    return render(request, "register.html", {"form": form})


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # Update the session to maintain the user's login status
            update_session_auth_hash(request, user)
            messages.success(request, "Your password was successfully updated!")
            return redirect("login")
        else:
            messages.error(request, "Please correct the error below.")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "change_password.html", {"form": form})

accounts/templates/change_password.html
<!-- change_password.html -->
{% extends 'dashboard/dashboard.html' %}

{% block content %}
    <h2>Change Password</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change password</button>
    </form>
{% endblock %}

accounts/templates/confirm.html
{% extends "core/Base.html" %} {% load static %}
<!---->
{% block content %}
<div class="school-thanks">
  <div class="thanks">
    <h1><i class="fa fa-check"></i></h1>
    <h4>School created succesfully</h4>
    <p>
      Please check The headteacher or Games teacher's email for your login credentials 
    </p>
  </div>
</div>
{% endblock %}

accounts/templates/filter_album.html
<!-- templates/filter_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Filter Form</title>
</head>
<body>
    <h1>Filter Form</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Filter Athletes and Officials</button>
    </form>
</body>
</html>

accounts/templates/login.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{%endblock%} USSSA | login</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/main/main.css'%}"
    />
    <link rel="stylesheet" href="{% static 'css/css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main/login.css'%}" />
  </head>
  <body>
    <div class="account">
      <div class="flex-account">
        <img src="{% static 'images/upsa.png'%}" class="logoz" alt="logo" />
        <form method="POST" action="" class="form-ctrl">
          {% csrf_token %}
          <!---->

          <div class="field">
            <i class="fa fa-user"></i>
            <input
              type="text"
              class="form-control"
              name="username"
              placeholder="Username"
              required
            />
          </div>

          <div class="field">
            <i class="fa fa-lock"></i>
            <input
              type="password"
              class="form-control"
              name="password"
              placeholder="Password"
              id="Password"
              required
            />
            <i class="fa fa-eye" id="eye" onclick="passview()"></i>
          </div>

          <button type="submit" class="btn-submit">Login</button>
        </form>
        <a href="/" class="home">Back to home</a
        >
        <br>
        <a href="{% url 'password_reset' %}"><i>Forgot Password?</i></a>
      </div>
    </div>
    <script>
      const password = document.getElementById("Password");
      const eye = document.querySelector("#eye");

      const passview = () => {
        if (password.type == "password") {
          password.type = "text";
          eye.classList.remove("fa-eye");
          eye.classList.add("fa-eye-slash");
        } else {
          password.type = "password";
          eye.classList.remove("fa-eye-slash");
          eye.classList.add("fa-eye");
        }
      };
    </script>
  </body>
</html>

accounts/templates/maintenance.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>UPSSA</title>
    <link rel="stylesheet" href="{% static 'css/maint.css'%}" />
  </head>
  <body>
    <div class="registration">
      <div class="registration-insider">
        <div class="logo">
          <img src="{% static 'images/upsa.png'%}" alt="" />
        </div>
        <h1>registration closed</h1>
        <p>Please use the dedicated helplines for assistance</p>
      </div>
    </div>
  </body>
</html>

accounts/templates/offcom.html
{% extends "core/Base.html" %} {% load static %}
<!---->
{% block content %}
<div class="school-thanks">
  <div class="thanks">
    <h1><i class="fa fa-check"></i></h1>
    <h4>Profile created succesfully</h4>
    <p>
      Please wait while we review the submitted data you will receive your Account details shortly via email
    </p>
  </div>
</div>
{% endblock %}

accounts/templates/ofifcom.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card text-center">
          <div class="card-body">
            <div class="mb-4">
              <i class="fas fa-check-circle text-success fa-4x"></i>
            </div>
            <h2 class="card-title mb-3">Profile Created Successfully</h2>
            <p class="card-text lead">
              Please wait while we review the submitted data.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>

accounts/templates/page404.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>404 </title>

    <!-- Custom stlylesheet -->
    <link
      rel="stylesheet"
      {% comment %} type="text/css" {% endcomment %}
      href="{% static 'css/main/not.css' %}"
    />
  </head>

  <body>
    <div class="pagenotfound">
      <div class="notfound">
        <div class="notfound-404">
          <h1>4<span>0</span>4</h1>
        </div\
        >
        <p>
          The page you are looking for might have been removed had its name
          changed or is temporarily unavailable.
        </p>
        {% if user.is_authenticated %}
        <a href="{%url 'dashboard'%}">Dashboard</a>{% else %}
        <a href="{%url 'login'%}">Login</a>{% endif %}
      </div>
    </div>
  </body>
</html>

accounts/templates/password_reset.html
{% extends "core/Base.html" %}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <div id="error_div"></div>
                          <h3 class="font-weight-light my-4 text-center">Forgot Password?</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                    <div class="form-group">
                                      <label class="small mb-1" for="id_email">Email</label>
                                        <input type="email" name="email"  class="form-control"
                                               autocomplete="email" maxlength="254" required id="id_email"
                                               placeholder="Enter email">
                                    </div>
                                </div>
                            </div>
                                <div class="form-row">
                                  <div class="col-md-10 offset-md-1">
                                    <div class="form-group mt-0 mb-1">
                                        <button type="submit" class="col-md-12 btn btn-dark">Submit
                                        </button>
                                    </div>
                                 </div>
                               </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                               
                                <a href="{% url 'login' %}">Back To Login</a><br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

  </div>
{% endblock content %}

accounts/templates/password_reset_complete.html
{% extends "core/Base.html" %}
{% block content %}
    <div class="container my-3 p-3">
        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                    <div class="alert alert-info">
                        Your password has been set. You may go ahead and <a href="{% url 'login' %}">Login Here</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

accounts/templates/password_reset_confirm.html
{% extends "core/Base.html" %}
<!---->
{% block title %} Password Reset {% endblock title%}
<!---->
{% block content %}
<div class="form-content my-3 p-3">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        {% if validlink %}
        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
          <div class="card-header justify-content-center">
            <h3 class="font-weight-light my-4 text-center">
              Reset Your Password
            </h3>
          </div>
          {% if form.errors %}
          <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
              {% for key, value in form.errors.items %}
              <strong>{{ value }}</strong>
              {% endfor %}
            </div>
            <button
              type="button"
              class="close"
              data-dismiss="alert"
              aria-label="Close"
            >
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}

          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1" for="id_new_password1"
                      >New Password</label
                    >
                    <input
                      type="password"
                      name="new_password1"
                      autocomplete="new-password"
                      class="form-control"
                      required
                      id="id_new_password1"
                      placeholder="Enter password"
                    />
                    <span> </span>
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group">
                    <label class="small mb-1" for="id_new_password2"
                      >New Password Confirmation</label
                    >
                    <input
                      type="password"
                      name="new_password2"
                      autocomplete="new-password"
                      required
                      id="id_new_password2"
                      class="form-control"
                      placeholder="Confirm password"
                    />
                  </div>
                </div>
              </div>
              <div class="form-row">
                <div class="col-md-10 offset-md-1">
                  <div class="form-group mt-0 mb-1">
                    <button
                      type="submit"
                      class="col-md-12 btn btn-dark"
                      id="reset"
                    >
                      Reset Password
                    </button>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
        {% else %}
        <div class="alert alert-warning">
          The password reset link was invalid, possibly because it has already
          been used. Please request a new password reset.
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

accounts/templates/password_reset_email.html
{% autoescape off %}
  To initiate the password reset process for your {{ user.email }} UPSSA Registration/Login Account,
  click the link below:

  {{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

  If clicking the link above doesn't work, please copy and paste the URL in a new browser
  window instead.

  Sincerely,
  The UPSSA IT TEAM
{% endautoescape %}

accounts/templates/profile_wizard.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
  </body>
</html>

accounts/templates/register.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title%}{%endblock%} USSSA | Register</title>
    <link rel="stylesheet" href="{% static 'css/main/main.css'%}" />
    <link rel="stylesheet" href="{% static 'css/css/all.min.css'%}" />
    <link rel="stylesheet" href="{% static 'css/main/register.css'%}" />
  </head>
  <body>
    <div class="account flex">
      <div class="flex_account grid2">
        <div class="lefta flex">
          <img src="{% static 'images/upsa.png'%}" alt="" />
          <h1>Welcome to USSSA IMS</h1>
          <p>
            We identify, nurture, develope and promote sports talent in schools
          </p>
          <p>
            By registering you agree to USSSA
            <a href="#">Terms and Conditions</a>
          </p>
          {% for message in messages %}
          <p>{{message}}</p>
          {% endfor %}
        </div>
        <div class="left">
          <form
            method="POST"
            action=""
            class="form-ctrl"
            enctype="multipart/form-data"
          >
            {% csrf_token %}
            <div class="fields grid2">
              <div class="field">
                <i class="fa fa-user"></i>
                <input
                  type="text"
                  name="first_name"
                  maxlength="255"
                  required=""
                  id="id_first_name"
                  placeholder="First name"
                />
              </div>
              <div class="field">
                <i class="fa fa-user"></i>
                <input
                  type="text"
                  name="last_name"
                  maxlength="255"
                  required=""
                  id="id_last_name"
                  placeholder="Last name"
                />
              </div>
            </div>
            <div class="fields grid2">
              <div class="field">
                <i class="fa fa-phone"></i>
                <input
                  type="text"
                  name="phone"
                  maxlength="20"
                  id="id_phone"
                  placeholder="Phone"
                />
              </div>
              <div class="field">
                <i class="fa fa-user"></i>
                <input
                  type="text"
                  name="username"
                  maxlength="150"
                  autofocus=""
                  required=""
                  id="id_username"
                  placeholder="Username"
                />
              </div>
            </div>
            <div class="fields">
              <div class="field">
                <i class="fa fa-envelope"></i>
                <input
                  type="email"
                  name="email"
                  maxlength="100"
                  required=""
                  id="id_email"
                  placeholder="Email"
                />
              </div>
            </div>
            <div class="fields grid2">
              <div class="field">
                <i class="fa fa-lock"></i>
                <input
                  type="password"
                  name="password1"
                  autocomplete="new-password"
                  required=""
                  id="id_password1"
                  placeholder="Password"
                />
              </div>
              <div class="field">
                <i class="fa fa-lock"></i>
                <input
                  type="password"
                  name="password2"
                  autocomplete="new-password"
                  required=""
                  id="id_password2"
                  placeholder="Confirm password"
                />
              </div>
            </div>

            <button type="submit" class="btn-submit">register</button>
            <div class="acct flex">
             
              <a href="{% url 'login'%}">login</a>
            </div>
          </form>
          <!--form for the school-->
        </div>
      </div>
    </div>
  </body>
</html>