asshu/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.urls import path
from teachers.views import *
from base.views import *


urlpatterns = [
    path("admin/", admin.site.urls),
    # venues
    path("",home,name='home'),
    path("teachers/", include("teachers.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from .views import *

from .views import *


urlpatterns = [
    # venues
    path("addteacher/", Teachera, name="addteacher"),
    # path("teccred/", teccreditation, name="teccred"),
    path('export-csv/', export_csv, name='export_csv'),
    path("teachers/", Teachers, name="teachers"),
    path("teacher/<int:id>", teacher_details, name="teacher"),
    path("delete_teacher/<int:id>", teacher_delete, name="delete_teacher"),
    path("update_teacher/<int:id>", teacher_update, name="update_teacher"),
    # path("process-payment/", process_payment, name="process_payment"),  # Add this line
    # Add more URLs as ne
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/models.py
from django.db import models
from accounts.models import District,Region

# Create your models here.


class Teacher(models.Model):

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    photo = models.ImageField(
        upload_to="photo/",
    )

    district = models.ForeignKey(
        District,
        related_name="district",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    region = models.ForeignKey(
        Region,
        related_name="region",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )

    contact = models.CharField(max_length=15)
    school = models.CharField(max_length=125)

    gender = models.CharField(
        max_length=14,
        choices=[("Male", "Male"), ("Female", "Female")],
    )
    designation = models.CharField(
        max_length=40,
        choices=[
            ("Principal", "Principal"),
            ("HeadTeacher", "HeadTeacher"),
            ("Deputy HeadTeacher", "Deputy HeadTeacher"),
        ],
    )

    def __str__(self):
        return self.first_name

teachers/forms.py
from django import forms
from dashboard.models import *
from .models import *


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            "first_name",
            "last_name",
            "designation",
            "photo",
            "contact",
            "region",
            "district",
            "gender",
            "school",
        ]
        widgets = {
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "school": forms.TextInput(attrs={"class": "form-control"}),
            "contact": forms.TextInput(attrs={"class": "form-control"}),
            "designation": forms.Select(attrs={"class": "form-control"}),
            "region": forms.Select(attrs={"class": "form-control"}),
            "district": forms.Select(attrs={"class": "form-control"}),
            "gender": forms.Select(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super(TeacherForm, self).__init__(*args, **kwargs)
        self.fields["photo"].widget.attrs["onchange"] = "displayImage(this);"

teachers/views.py
from django.shortcuts import render, redirect, get_object_or_404

from xhtml2pdf import pisa
from django.template.loader import get_template
from django.http import HttpResponse


from django.contrib import messages


# from dashboard.filters import *
from xhtml2pdf import pisa
from io import BytesIO

# Create your views here.
from .models import *
from .forms import *


def Teachera(request):

    if request.method == "POST":
        form = TeacherForm(request.POST, request.FILES)

        if form.is_valid():
            # admin_user = User.objects.get_or_create(username="admin")
            # Assign the currently logged-in user
            form.save()
            messages.success(request, "Form submitted successfully!")
            return redirect("addteacher")

        else:
            # Add form-specific error messages for individual fields
            messages.error(request, "Form is not valid. Please check your input.")
            print(f"Form errors: {form.errors}")

    else:
        form = TeacherForm()

    context = {"form": form}
    return render(request, "teacher_new.html", context)


# def nOfficials(request):
#     # Get all officials
#     nofficials = NOC.objects.all()

#     # Apply the filter
#     official_filter = nocFilter(request.GET, queryset=nofficials)
#     filtered_officials = official_filter.qs

#     if request.method == "POST":
#         # Check which form was submitted
#         if "Accreditation" in request.POST:
#             template = get_template("noc/accreditation.html")
#             filename = "Filtered_Accreditation.pdf"
#         elif "Certificate" in request.POST:
#             template = get_template("teams/offcert.html")  # Your certificate template
#             filename = "Filtered_Certificate.pdf"
#         else:
#             return HttpResponse("Invalid form submission")

#         # Generate PDF
#         context = {"officials": filtered_officials}
#         html = template.render(context)

#         # Create a PDF
#         pdf_buffer = BytesIO()
#         pisa_status = pisa.CreatePDF(html, dest=pdf_buffer)

#         if pisa_status.err:
#             return HttpResponse("We had some errors <pre>" + html + "</pre>")

#         pdf_buffer.seek(0)

#         # Return the PDF as a response
#         response = HttpResponse(content_type="application/pdf")
#         response["Content-Disposition"] = f'attachment; filename="{filename}"'
#         response.write(pdf_buffer.getvalue())
#         return response
#     else:
#         # Render the filter form
#         return render(request, "noc/noffs.html", {"filter": official_filter})


from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import BytesIO


from .filters import TeacherFilter  # Assume you have created this filter


def Teachers(request):
    # Get all teachers
    teachers = Teacher.objects.all()

    # Apply the filter
    teacher_filter = TeacherFilter(request.GET, queryset=teachers)
    filtered_teachers = teacher_filter.qs

    if request.method == "POST":
        # Check which form was submitted
        if "Accreditation" in request.POST:
            template = get_template("acred.html")
            filename = "Asshu_Accreditation.pdf"
        elif "Certificate" in request.POST:
            template = get_template(
                "certificate_temaplate.html"
            )  # Your certificate template
            filename = "Filtered_Certificate.pdf"
        else:
            return HttpResponse("Invalid form submission")

        # Generate PDF
        context = {"teachers": filtered_teachers}
        html = template.render(context)

        # Create a PDF
        pdf_buffer = BytesIO()
        pisa_status = pisa.CreatePDF(html, dest=pdf_buffer)

        if pisa_status.err:
            return HttpResponse("We had some errors <pre>" + html + "</pre>")

        pdf_buffer.seek(0)

        # Return the PDF as a response
        response = HttpResponse(content_type="application/pdf")
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response.write(pdf_buffer.getvalue())
        return response
    else:
        # Render the filter form
        return render(request, "teachers.html", {"filter": teacher_filter})



def teacher_details(request, id):
    teacher = Teacher.objects.get(id=id)

    context = {"teacher": teacher}
    return render(request, "teacher.html", context)


def teacher_update(request, id):
    teacher = get_object_or_404(Teacher, id=id)

    if request.method == "POST":
        form = TeacherForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            form.save()
            messages.success(request, "Teacher information updated successfully!")
            return redirect("teacher", id=teacher.id)
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        form = TeacherForm(instance=teacher)

    context = {
        "form": form,
        "teacher": teacher,
    }
    return render(request, "update_teacher.html", context)


def teacher_delete(request, id):
    stud = Teacher.objects.get(id=id)
    if request.method == "POST":
        stud.delete()
        return redirect("teachers")

    return render(request, "delete_teacher.html", {"obj": stud})


import csv
from django.http import HttpResponse


def export_csv(request):
    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="data.csv"'

    # Create a CSV writer object using the HttpResponse as the file.
    writer = csv.writer(response)

    # Write the header row
    writer.writerow(
        [
            "id",
            "first_name",
            "last_name",
            "school",
            "designation",
            "contact",
            "district",
            "region",
        ]
    )  # Replace with your model's fields

    # Write data rows
    for obj in Teacher.objects.all():
        writer.writerow(
            [
                obj.id,
                obj.first_name,
                obj.last_name,
                obj.school,
                obj.designation,
                obj.contact,
                obj.district,
                obj.region,
            ]
        )  # Replace with your model's fields

    return response

teachers/templates/acred.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Album</title>
  </head>

  <body>
    <style>
      @media print {
        @page {
          size: A4 portrait; /* Set the size of the page to A4 in portrait orientation */
          margin: 0; /* Remove default margin */
        }

        body {
          margin: 0; /* Remove default body margin */
          padding: 0; /* Remove default body padding */
        }

        .athletes table {
          display: grid;
          grid-template-rows: repeat(2, 1fr); /* Two rows */
          grid-template-columns: repeat(2, 1fr); /* Two columns */
          gap: 10px; /* Adjust the gap between grid items */
        }
      }
      .header .athletes table tbody tr td table tr .td {
        padding-top: 105px;
        padding-bottom: 40px;
        padding-left: 50px;
        padding-right: 40px;
        margin: 0;
      }
      .header .athletes table tbody tr td table tr .td .inner {
        width: 350px;
        text-align: center;
        text-transform: uppercase;
      }
      .header .athletes table tbody tr td table tr .td .inner img {
        width: 160px;
        height: 160px;
        image-orientation: from-image;
        transform: rotate(0deg);
      }
      .header .athletes table tbody tr td table tr .td .inner span {
      }
    </style>
    <div class="header">
      <div class="athletes">
        <table>
          <tbody>
            {% for athlete in teachers %}
            <!---->
            {% if forloop.counter0|divisibleby:2 %}
            <!-- Start a new row for every even-numbered athlete -->
            <tr>
              {% endif %}
              <td>
                <table>
                  <tr>
                    <td class="td">
                      <div class="inner">
                        <span
                          >{{ athlete.contact|upper}}
                          ({{athlete.gender|upper}})</span
                        >
                        <br />
                        {% if athlete.photo %}
                        <img
                          src="{{ athlete.photo.path }}"
                          alt="{{ athlete.first_name }}"
                        />
                        {% else %}
                        <img
                          src="{% static 'images/profile.png' %}"
                          alt="{{ athlete.last_name }}"
                        />
                        {% endif %}
                        <br />
                        <span
                          >{{ athlete.first_name|upper }}
                          {{athlete.last_name|upper }}
                        </span>
                        <br />
                        <span>{{ athlete.designation|upper }}</span><br />
                        <span>{{ athlete.school|upper }}</span><br />
                        <span>{{ athlete.district|upper }}</span><br />
                      </div>
                    </td>
                  </tr>
                </table>
              </td>
              {% if forloop.last or forloop.counter0|add:1|divisibleby:2 %}
              <!-- End the row for the last or odd-numbered athlete -->
            </tr>
            {% endif %} {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

teachers/templates/certificate_temaplate.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Album</title>
  </head>

  <body>
    <style>
      @page {
        size: A4 portrait;
        margin: 0;
      }
      body {
        margin: 0;
        padding: 0;
      }
      .teacher-table {
        width: 100%;
        border-collapse: collapse;
      }
      .header .teachers table tbody tr td {
        padding-top: 290px;
        padding-left: 70px;
        padding-right: 30px;
        margin: 0;
      }
      .header .teachers table tbody tr .teacher-cell .teacher-info {
        font-size: 1.4em; /* Adjust font size */
        text-align: center; /* Align text to the left */
        width: 800px; /* Set a fixed width to ensure text fits on one line */
      }
      .header .teachers table tbody tr .teacher-cell .teacher-image img {
        width: 120px;
        height: 120px;
        image-orientation: from-image;
        transform: rotate(0deg);
      }
    </style>
    <div class="header">
      <div class="teachers">
        <table class="teacher-table">
          <tbody>
            {% for teacher in teachers %}
            <tr>
              <td class="teacher-cell">
                <div class="teacher-info">
                  <span
                    ><strong
                      >{{ teacher.first_name|upper }}
                      {{teacher.last_name|upper}}
                    </strong></span
                  ><br />

                  <span>{{ teacher.designation|upper }}</span><br />
                  <span>{{ teacher.school|upper }}</span><br />
                  <span>{{ teacher.district|upper }} </span><br />
                </div>
              </td>
              <td class="teacher-cell">
                <div class="teacher-image">
                  {% if teacher.photo %}
                  <img
                    src="{{ teacher.photo.path }}"
                    alt="{{ teacher.first_name }}"
                  />
                  {% else %}
                  <img
                    src="{% static 'images/profile.png' %}"
                    alt="{{ teacher.last_name }}"
                  />
                  {% endif %}
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

teachers/templates/delete_teacher.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Delete Confirmation</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
  </head>
  <body>
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="card">
            <div class="card-body">
              <form action="" class="formdelete" method="POST">
                {% csrf_token %}
                <h5 class="card-title">Confirm Deletion</h5>
                <p class="card-text">
                  Are you sure you want to delete <strong>{{ obj }}</strong>?
                </p>
                <hr />
                <div class="d-flex justify-content-between">
                  <input type="submit" value="Confirm" class="btn btn-danger" />
                  <a
                    href="{{ request.META.HTTP_REFERER }}"
                    class="btn btn-secondary"
                    >Cancel</a
                  >
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

teachers/templates/teacher.html
{% extends "dashboard/dashboard.html" %}
<!--static-->
{% block title %}{{teacher.first_name}} {{teacher.last_name}}{% endblock %}
<!--static-->
{% load static %}
<!--khfufufu-->
{% block content %}
<div class="schools-den">
  <div class="head flex">
    <h1>{{teacher.first_name}} {{teacher.last_name}}</h1>
    <hr />
  </div>
  <div class="imagebox">
    <img src="{{teacher.photo.url}}" alt="" />
    <div class="details">
      <li>{{teacher.first_name}} {{teacher.last_name}}</li>
      <li>{{teacher.school}}</li>

      <li>{{teacher.region}}</li>

      <li>{{teacher.district}}</li>

      <li>{{teacher.designation}}</li>

      <li>{{teacher.contact}}</li>
    </div>
  </div>
</div>

{% endblock %}

teachers/templates/teacher_new.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ASSHU | REGISTRATION{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{%static 'images/asshu.png'%}" sizes="35x35" />
    <link rel="stylesheet" href="{% static 'css/profile/school_new.css'%}" />
    <link rel="stylesheet" href="{% static 'css/base/base.css'%}" />
    <link rel="stylesheet" href="{% static 'css/maint.css'%}" />

    <script
      src="https://code.jquery.com/jquery-2.1.1.min.js"
      type="text/javascript"
    ></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
        $("#id_district").select2();
      });
    </script>
  </head>
  <body>
    <div class="profile-update">
      <div class="school-long">
        <div class="head flex">
          <img src="{% static 'images/asshu.png' %}" id="dw" alt="No Photo" />
          <div class="hedtxt">
            <h2>Annual General Meeting</h2>
          </div>
        </div>
        <form
          action=""
          method="POST"
          class="form-ctrl"
          enctype="multipart/form-data"
        >
          {% csrf_token %}

          <div class="school">
            <div class="fields">
              <div class="left">
                {{ cform.non_field_errors }} {{ cform.errors }}
                <!---->
                {% if messages %}
                <ul class="messages">
                  {% for message in messages %}
                  <li
                    class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}"
                  >
                    {{ message }}
                  </li>
                  {% endfor %}
                </ul>
                {% endif %}
                <div class="imgbox">
                  <div class="field">
                    <label>{{form.photo.label}}</label>

                    {% if form.instance.photo %}
                    <img
                      src="{{ form.instance.photo.url }}"
                      id="image-preview"
                      alt="Current Photo"
                    />
                    {% else %}
                    <img
                      src="{% static 'images/logos.jpg' %}"
                      id="image-preview"
                      alt="No Photo"
                    />
                    {% endif %}
                  </div>
                  <div class="field">
                    <input
                      type="file"
                      name="photo"
                      accept="image/*"
                      onchange="displayImage(this);"
                      id="id_photo"
                    />
                  </div>
                </div>
              </div>
              <div class="fiil">
                <div class="filflex">
                  <div class="field">
                    <label>First Name</label>
                    {{form.first_name}}
                  </div>
                  <div class="field">
                    <label>Last Name</label>
                    {{form.last_name}}
                  </div>
                </div>
                <div class="field">
                  <label>School</label>
                  {{form.school}}
                </div>
                <div class="filflex">
                  <div class="field">
                    <label>Phone:</label>
                    {{form.contact}}
                  </div>
                  <div class="field">
                    <label>Role:</label>
                    {{form.designation}}
                  </div>
                </div>
                <div class="filflex">
                  <div class="field">
                    <label>gender</label>
                    {{form.gender}}
                  </div>
                  <div class="field">
                    <label>Region</label>
                    {{form.region}}
                  </div>
                </div>
                <div class="field">
                  <label>District/ City/ Municipality</label>
                  {{form.district}}
                </div>

                <button type="submit" class="btn btn-success">Submit</button>
                
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    <script>
      function displayImage(input) {
        var reader = new FileReader();
        reader.onload = function (e) {
          document.getElementById("image-preview").src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
      }
    </script>
  </body>
</html>

teachers/templates/teachers.html
{% extends "dashboard/dashboard.html" %}

<!--static-->
{% block title %}Officials{% endblock %}
<!--static-->
{% load static %}
<!--khfufufu-->
{% block content %}
<div class="schools-dew">
  <div class="head flex">
    <h1>ASSHU</h1>
    <hr />
  </div>
  <div class="filter">
    <h2>Filter Teachers</h2>
    <form method="get" class="form-contol">
      {{ filter.form.as_p }}
      <button type="submit">Apply Filter</button>
    </form>
    <form method="post" class="form-contol">
      {% csrf_token %}
      <input type="submit" name="Accreditation" value="Accreditation" />
    </form>
 
    <form method="post" class="form-contol">
      {% csrf_token %}
      <input type="submit" name="Certificate" value="Certificate" />
    </form>
    <a href="{% url 'export_csv' %}">Export CSV</a>
  </div>
  <div class="filterlist glue">
    <div class="official-list">
      <table id="myTable" class="display">
        <thead>
          <tr>
            <th>Names</th>
            <th>School</th>
            <th>Designation</th>
            <th>Region</th>
            <th>District</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
        </thead>
        <tbody>
          {% for teacher in filter.qs %}
          <tr>
            <td>
              <a href="{% url 'teacher' teacher.id%}"
                >{{teacher.first_name}} {{teacher.last_name}}</a
              >
            </td>
            <td>{{teacher.school}}</td>
            <td>{{teacher.designation}}</td>
            <td>{{teacher.region}}</td>

            <td>{{teacher.district}}</td>
            <td><a href="{%url 'update_teacher' teacher.id %}">Edit</a></td>
            <td><a href="{%url 'delete_teacher' teacher.id %}">delete</a></td>
          </tr>

          {%endfor%}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}

teachers/templates/update_teacher.html
<html lang="en">
  {% load static %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ASSHU | REGISTRATION{% block title %}{% endblock title %}</title>
    <link rel="icon" href="{%static 'images/asshu.png'%}" sizes="35x35" />
    <link rel="stylesheet" href="{% static 'css/profile/school_new.css'%}" />
    <link rel="stylesheet" href="{% static 'css/base/base.css'%}" />
    <link rel="stylesheet" href="{% static 'css/maint.css'%}" />

    <script
      src="https://code.jquery.com/jquery-2.1.1.min.js"
      type="text/javascript"
    ></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/css/select2.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.1/js/select2.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function () {
        $("#id_district").select2();
      });
    </script>
  </head>
  <body>
    <div class="profile-update">
      <div class="school-long">
        <div class="head flex">
          <img src="{% static 'images/asshu.png' %}" id="dw" alt="No Photo" />
          <div class="hedtxt">
            <h2>Annual General Meeting</h2>
          </div>
        </div>
        <form
          action=""
          method="POST"
          class="form-ctrl"
          enctype="multipart/form-data"
        >
          {% csrf_token %}

          <div class="school">
            <div class="fields">
              <div class="left">
                <div class="imgbox">
                  <div class="field">
                    <label>{{form.photo.label}}</label>

                    {% if form.instance.photo %}
                    <img
                      src="{{ form.instance.photo.url }}"
                      id="image-preview"
                      alt="Current Photo"
                    />
                    {% else %}
                    <img
                      src="{% static 'images/logos.jpg' %}"
                      id="image-preview"
                      alt="No Photo"
                    />
                    {% endif %}
                  </div>
                  <div class="field">
                    <input
                      type="file"
                      name="photo"
                      accept="image/*"
                      onchange="displayImage(this);"
                      id="id_photo"
                    />
                  </div>
                </div>
              </div>
              <div class="fiil">
                <div class="filflex">
                  <div class="field">
                    <label>First Name</label>
                    {{form.first_name}}
                  </div>
                  <div class="field">
                    <label>Last Name</label>
                    {{form.last_name}}
                  </div>
                </div>
                <div class="field">
                  <label>School</label>
                  {{form.school}}
                </div>
                <div class="filflex">
                  <div class="field">
                    <label>Phone:</label>
                    {{form.contact}}
                  </div>
                  <div class="field">
                    <label>Role:</label>
                    {{form.designation}}
                  </div>
                </div>
                <div class="filflex">
                  <div class="field">
                    <label>gender</label>
                    {{form.gender}}
                  </div>
                  <div class="field">
                    <label>Region</label>
                    {{form.region}}
                  </div>
                </div>
                <div class="field">
                  <label>District/ City/ Municipality</label>
                  {{form.district}}
                </div>

                <button type="submit" class="btn btn-success">Submit</button>
                {{ cform.non_field_errors }} {{ cform.errors }}
                <!---->
                {% if messages %}
                <ul class="messages">
                  {% for message in messages %}
                  <li
                    class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %}"
                  >
                    {{ message }}
                  </li>
                  {% endfor %}
                </ul>
                {% endif %}
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    <script>
      function displayImage(input) {
        var reader = new FileReader();
        reader.onload = function (e) {
          document.getElementById("image-preview").src = e.target.result;
        };
        reader.readAsDataURL(input.files[0]);
      }
    </script>
  </body>
</html>